defaults:
  - benchmark
  - scenario: inference
  # - launcher: inline #process
  - backend: pytorch
  - _base_
  - _self_

name: cuda_pytorch_mamba2.8-ssm_repo

# launcher:
#   device_isolation: true
#   device_isolation_action: warn

backend:
  device: cuda
  device_ids: 0
  no_weights: false
  model: state-spaces/mamba-2.8b
  model_type: mamba_ssm_repo
  model_kwargs:
    dtype: float16

scenario:
  input_shapes:
    batch_size: 8
    sequence_length: 256

  generate_kwargs:
    cg: True
    repetition_penalty: 1.2
